### ISSUE TITLE
Memory leak in keyring.js model? (Firefox / macos)

### ISSUE THREAD

**Issue by pomarec** [passbolt/passbolt_browser_extension#9] opened 2017-02-13 17:28 UTC
Without passbolt -> ~ 4GB
With passbolt -> ~35GB
Mesured with htop

Is this expected ? Is this wanted ?

Firefox 51.0.1 (64 bits)
Macos x 10.11.6

**Comment by pomarec** [comment] 2017-02-14 13:41
More info, after a llittle investigation it may come from line 11 in keyring model. If I comment the requirement of openpgp (and code that uses it) I no longer have this memory usage.

**Comment by stripthis** [comment] 2017-02-14 14:20
Thank you for reporting this issue. We are not able to reproduce this issue at the moment but we will have a look.

**Comment by pomarec** [comment] 2017-02-14 14:28
I proposed a PR https://github.com/passbolt/passbolt_browser_extension/pull/10

**Comment by stripthis** [comment] 2017-02-17 15:44
Merged with v1.4.0 thank you for your contribution @pomarec !

**Closed by stripthis** 2017-02-17 15:44 UTC
Labels: bug
