### ISSUE TITLE
Firefox content runs noticeably slower whenever Passbolt extension is present

### ISSUE THREAD

**Issue by sirikon** [passbolt/passbolt_browser_extension#169] opened 2023-02-06 19:28 UTC
* Passbolt Version: Extension is version 3.9.2
* Platform and Target:
-- Browser: Firefox 109.0.1
-- OS: Linux (Debian Bullseye)
-- Arch: x86-64

### What you did
- Install Passbolt
- Allow Passbolt to work on private browsing, let it be the only allowed extension in private browsing.
- Open a new private browsing window and navigate to http://meteomars.pamplonetario.org/
- Pick one of the images at the right and then spin around the globe. Moves around with really low FPS
- Disallow Passbolt to work on private browsing.
- FPS immediately increases, a lot.
- Allow Passbolt again.
- FPS stays up
- Reload page
- FPS is back down.

I know, it sounds REALLY weird, but I swear it's what's happening. There's a video attached, hope the FPS drop is noticeable in it.

https://user-images.githubusercontent.com/1157382/217065978-76ff9f3c-612b-4329-87cb-06985ef90264.mp4

**Comment by cedricalfonsi** [comment] 2023-08-29 13:39
Hello @sirikon,

Sorry for the delay, we should have answered long time back.

Few releases happened since the v3.9.2 and with it some major changes. 
Could you please confirm the issue is still happening? Here an attempt was made to kill the performance of the machine with over 10k passwords loaded in passbolt, and everything seems smooth, but it might be due to the hardware.

If you are still encountering the issue, can you please provide us with information regarding your hardware and passbolt number of resources under management.

**Comment by cedricalfonsi** [comment] 2023-08-29 15:17
Thank you for the follow-up ❤️ 

The machine seems pretty solid and not much passwords are under management. The algorithm responsible to search credential fields on the visited pages was improved with the latest releases, and it is very much possible that it was at the origin of this issue. I keep the tool you provided to test the performances, it's both interesting and practical.

I'm closing the issue in the meantime, as it seems fixed.

Thank you again, and maybe see you later ^^

**Closed by cedricalfonsi** 2023-08-29 15:17 UTC
Labels: cannot reproduce

**Comment by davemc50** [comment] 2025-09-09 09:18
This issue still happens.  It is very noticeable in web pages that interact with the keyboard a lot, noteably Facebook and Microsoft Outlook & Word when typing emails or documents.  It seems that PB extension is noseying into every keypress, as are facecrook and m$oft. The combination of both seems to create the slowdown.

Firefox on Kubuntu
