### ISSUE TITLE
Create new id | Edge extension stuck

### ISSUE THREAD

**Issue by Ctixou** [passbolt/passbolt_browser_extension#222] opened 2024-10-24 13:09 UTC
Hello,

## ISSUE NAME
* Passbolt Version: 4.9.4
* Platform and Target: Windows edge
-- Browser: edge 130.0.2849.52

### What you did
Just want to create a new id from website

### What happened
The page where I have to write informations is stuck when I click on "Enregistrer" (register)

### What you expected to happen
The page should be closed after I clicked on register and save my id and password
![passbolt](https://github.com/user-attachments/assets/e9ca01df-a81e-449e-bfea-d2ad8585b882)

**Comment by Gamabunta57** [comment] 2024-10-24 13:39
Hello @Ctixou!

I gave a check at your issue. I confirm, I can reproduce it 100% of the time.
Plus, I noticed other unexpected behaviours like the width of the opened window is a bit off, and the form is not automatically fulfilled with the information from the page.

I have created an internal ticket to solve the issue (PB-36484 for the reference).

I am currently investigating on it, and I'll keep you in touch when I have more info.

**Comment by Ctixou** [comment] 2024-10-24 13:42
Thank you @Gamabunta57 !

**Comment by Gamabunta57** [comment] 2024-10-24 14:17
After investigation it turns out that this problem has been fixed internally already. 
It's waiting for the next release to be published (the v4.10.0).

We'll start to release the fix in the next days (probably beginning of the incoming week). I'll keep you informed on the release of this version, notice however that the availability in the store will depend on the provider itself and not on us. So, even if we publish a new version soon MS Edge will take more days to make it available for you.

**Comment by cedricalfonsi** [comment] 2024-12-12 10:14
Fixed in v4.10.0.
Feel free to reopen if the problem persists @Ctixou.

**Closed by cedricalfonsi** 2024-12-12 10:14 UTC
Labels: bug
