### ISSUE TITLE
App/users page not load (Edge)

### ISSUE THREAD

**Issue by infraoderco** [passbolt/passbolt_browser_extension#215] opened 2024-08-16 14:39 UTC
## ISSUE NAME
* Passbolt Version: 4.9.1
* Platform and Target: Docker
-- Browser: Edge 127.0.2651.98
-- Web server: PHP version 8.2.20
-- etc.: Server 4.9.1 Client 4.9.1

### What you did
I no longer think the problem is related to some incorrect configuration on our part, but rather some problem related to the browser extension. What I did was the following: We have a dedicated Passbolt server internally, but we decided to create another server in the cloud for better remote access and we started using it while the internal Passbolt was on standby. At the time, the user screen still worked normally, even on the cloud server, but it was before the last update of the extension. After this update to version 4.9.1 of the extension, after a while we noticed this problem of not opening the user screen and we started investigating if we had made some incorrect configuration.

Since I didn’t find anything, I decided as a last test to delete all the information and create a new server in Docker from scratch. After I created and added the first user, even without any information on the server, the same error occurred, the user screen didn’t open. So I decided to go back to using the internal server that was working, but when I did that, I saw that the same error also occurred. At that time, I was using Microsoft Edge along with the extension downloaded from the Edge extension store. However, on another computer that was still pointed to the internal server, the user screen was working normally, but in Google Chrome. So I tried doing the same on my machine and, to my surprise, it worked perfectly. So I believed that the problem was with the extension from the Edge store and decided to uninstall this extension from Microsoft Edge and download the extension from the Google Chrome store on Edge, and voilà, it worked!
So with that in mind, I went back to pointing my computer to Passbolt in the cloud and did the same procedures as before. Unfortunately, in this case, it still didn’t work. It’s still the same. So, since the server was created from scratch, without any information, and yet the same thing happens, I can only believe that the problem is really something with the Extension, since it has nothing to do with the server itself.

### What happened
The User's page not load

### What you expected to happen
To access the user and groups page

**Comment by infraoderco** [comment] 2024-08-16 14:51
Some errors in F12 are

![image](https://github.com/user-attachments/assets/f4638e15-43f7-45f3-99dc-98af040bc6a1)

![image](https://github.com/user-attachments/assets/1ae3814f-5682-49ed-9018-bf0ae8298586)

![image](https://github.com/user-attachments/assets/00f99ddc-177c-454c-88f2-054e93f379cb)

Remembering, the same problem occurs when I create a new fresh server with docker hub using latest tag passbolt

**Comment by cedricalfonsi** [comment] 2024-08-16 15:28
Hello @infraoderco,

Thank you for the bug report and the additional information.

Here is the internal follow-up ticket: PB-34421.

We were unable to reproduce the error using the same version of Edge and the latest API, and we did not encounter any issues.

Could you please confirm if the application is stuck in loading mode, as shown in the following screenshot:

<img width="1192" alt="Screenshot 2024-08-16 at 17 20 18" src="https://github.com/user-attachments/assets/a3cc17bd-9c43-4b09-85c8-0177971ee912">

Could you check the result of the users.json request to see if the data returned by the API includes users with their profiles, such as:

```
{
    "header": {
        "id": "0cfd3132-f7c5-4fd9-94a2-ccbe350fb5fa",
        "status": "success",
        "servertime": 1723821962,
        "action": "d7bc9044-a64e-5421-a4d7-7a94eaa39d37",
        "message": "The operation was successful.",
        "url": "\/users.json?api-version=v2\u0026contain%5Bprofile%5D=1\u0026contain%5Bgpgkey%5D=0\u0026contain%5Bgroups_users%5D=0\u0026contain%5Bpending_account_recovery_request%5D=1\u0026contain%5Baccount_recovery_user_setting%5D=1\u0026contain%5Bis_mfa_enabled%5D=1\u0026contain%5BLastLoggedIn%5D=1",
        "code": 200,
        "pagination": {
            "count": 1,
            "page": 1,
            "limit": null
        }
    },
    "body": [
        {
            "last_logged_in": "2024-08-16T20:49:55+05:30",
            "is_mfa_enabled": false,
            "id": "809ac4be-3e45-4100-ba4d-a3ab8ecc6e72",
            "role_id": "0d51c3a8-5e67-5e3d-882f-e1868966d817",
            "username": "admin@passbolt.com",
            "active": true,
            "deleted": false,
            "disabled": null,
            "created": "2024-08-16T20:34:25+05:30",
            "modified": "2024-08-16T20:35:03+05:30",
            "profile": {
                "id": "e5ae47ce-7215-43e1-b7e6-d60328b8b14a",
                "user_id": "809ac4be-3e45-4100-ba4d-a3ab8ecc6e72",
                "first_name": "yourname",
                "last_name": "surname",
                "created": "2024-08-16T20:34:25+05:30",
                "modified": "2024-08-16T20:34:25+05:30",
                "avatar": {
                    "url": {
                        "medium": "https:\/\/www.passbolt.test\/img\/avatar\/user_medium.png",
                        "small": "https:\/\/www.passbolt.test\/img\/avatar\/user.png"
                    }
                }
            },
            "role": {
                "id": "0d51c3a8-5e67-5e3d-882f-e1868966d817",
                "name": "admin",
                "description": "Organization administrator",
                "created": "2012-07-04T13:39:25+05:30",
                "modified": "2012-07-04T13:39:25+05:30"
            },
            "pending_account_recovery_request": null,
            "account_recovery_user_setting": null
        }
    ]
}
```

The network activity can be viewed in the browser extension debug:
- Go to edge://extensions/.
- Click on the "Details" link for the Passbolt extension.
- In the "Inspect views" section, click on index.html.

**Comment by infraoderco** [comment] 2024-08-16 17:12
> Hello @infraoderco,
> 
> Thank you for the bug report and the additional information.
> 
> Here is the internal follow-up ticket: PB-34421.
> 
> We were unable to reproduce the error using the same version of Edge and the latest API, and we did not encounter any issues.
> 
> Could you please confirm if the application is stuck in loading mode, as shown in the following screenshot:
> 
> <img alt="Screenshot 2024-08-16 at 17 20 18" width="1192" src="https://private-user-images.githubusercontent.com/1582917/358633198-a3cc17bd-9c43-4b09-85c8-0177971ee912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MjgyMzksIm5iZiI6MTcyMzgyNzkzOSwicGF0aCI6Ii8xNTgyOTE3LzM1ODYzMzE5OC1hM2NjMTdiZC05YzQzLTRiMDktODVjOC0wMTc3OTcxZWU5MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTcwNTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE4MGQ2YzYzN2NhOTQwNzBiYzBhNjYxMDMxYTg1NzA2ZGEyNTNlYjlkMWY0YzAzNzVhNDA0ZDlkZmJhNzVmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oIazrqPX09s2PmuMieD-lr1Rb_wxp6nIkLJ3WMIcMk4">
> Could you check the result of the users.json request to see if the data returned by the API includes users with their profiles, such as:
> 
> ```
> {
>     "header": {
>         "id": "0cfd3132-f7c5-4fd9-94a2-ccbe350fb5fa",
>         "status": "success",
>         "servertime": 1723821962,
>         "action": "d7bc9044-a64e-5421-a4d7-7a94eaa39d37",
>         "message": "The operation was successful.",
>         "url": "\/users.json?api-version=v2\u0026contain%5Bprofile%5D=1\u0026contain%5Bgpgkey%5D=0\u0026contain%5Bgroups_users%5D=0\u0026contain%5Bpending_account_recovery_request%5D=1\u0026contain%5Baccount_recovery_user_setting%5D=1\u0026contain%5Bis_mfa_enabled%5D=1\u0026contain%5BLastLoggedIn%5D=1",
>         "code": 200,
>         "pagination": {
>             "count": 1,
>             "page": 1,
>             "limit": null
>         }
>     },
>     "body": [
>         {
>             "last_logged_in": "2024-08-16T20:49:55+05:30",
>             "is_mfa_enabled": false,
>             "id": "809ac4be-3e45-4100-ba4d-a3ab8ecc6e72",
>             "role_id": "0d51c3a8-5e67-5e3d-882f-e1868966d817",
>             "username": "admin@passbolt.com",
>             "active": true,
>             "deleted": false,
>             "disabled": null,
>             "created": "2024-08-16T20:34:25+05:30",
>             "modified": "2024-08-16T20:35:03+05:30",
>             "profile": {
>                 "id": "e5ae47ce-7215-43e1-b7e6-d60328b8b14a",
>                 "user_id": "809ac4be-3e45-4100-ba4d-a3ab8ecc6e72",
>                 "first_name": "yourname",
>                 "last_name": "surname",
>                 "created": "2024-08-16T20:34:25+05:30",
>                 "modified": "2024-08-16T20:34:25+05:30",
>                 "avatar": {
>                     "url": {
>                         "medium": "https:\/\/www.passbolt.test\/img\/avatar\/user_medium.png",
>                         "small": "https:\/\/www.passbolt.test\/img\/avatar\/user.png"
>                     }
>                 }
>             },
>             "role": {
>                 "id": "0d51c3a8-5e67-5e3d-882f-e1868966d817",
>                 "name": "admin",
>                 "description": "Organization administrator",
>                 "created": "2012-07-04T13:39:25+05:30",
>                 "modified": "2012-07-04T13:39:25+05:30"
>             },
>             "pending_account_recovery_request": null,
>             "account_recovery_user_setting": null
>         }
>     ]
> }
> ```
> 
> The network activity can be viewed in the browser extension debug:
> 
> * Go to edge://extensions/.
> * Click on the "Details" link for the Passbolt extension.
> * In the "Inspect views" section, click on index.html.

Yes, the page stuck just like that.

I'm sorry, but I don't know so much the procedures, could you please explain where do I found the header like you said? When I check edge://extensions I didn't find the same information, I am noob with this. Thanks a lot for quick response

**Comment by cedricalfonsi** [comment] 2024-08-19 13:52
Hello @infraoderco,

Don't worry I will try to be clearer.

1. Open the browser extension manager by following the url: edge://extensions
![Screenshot 2024-08-19 at 15 41 29](https://github.com/user-attachments/assets/ea26dc64-3b04-4b63-b4e7-64fb10d14c58)

2. Open the passbolt developer tool.

To do so click on the index.html link displayed in the "inspect views" section of the passbolt extension.
![Screenshot 2024-08-19 at 15 45 02](https://github.com/user-attachments/assets/1c30d9f3-9ada-4e4b-9226-6f99e5b61837)

3. Open the "Network" tab of the developer tool that just opened. Look for the users.json and select it, in the right panel that just opened select the "Response" tab.
![Screenshot 2024-08-19 at 15 48 48](https://github.com/user-attachments/assets/401386ec-df06-4a13-963f-9d9dbe3254fb)

4. Ensure the response includes users with their profiles, such as as described in the previous screenshot.

**Comment by cedricalfonsi** [comment] 2024-10-25 15:34
Since we have not received further information and are unable to reproduce the issue, we are closing this bug report for now. If you encounter the issue again or have additional details, please feel free to reopen the report, and we will be happy to investigate further.

**Closed by cedricalfonsi** 2024-10-25 15:34 UTC
Labels: waiting for reporter feedback
