### ISSUE TITLE
Passbolt asks for my password too often

### ISSUE THREAD

**Issue by burasuk** [passbolt/passbolt_browser_extension#103] opened 2020-08-06 10:06 UTC
## Passbolt asks for my password too often
* Passbolt Version: 2.13.5
* Platform and Target:
-- Browser: Firefox 79 (64bit)
-- etc.: Windows 10, 64 bit

### What you did
Previously i was logged to passbolt.
I go to for example gitlab.com and use passbolt to paste credentials.

### What happened
First, when i try to sing in with passbolt, it ask me for password, when i log in, he paste credentials, great.
When i try to repeat this sequence, he ask me again for password.

![passbolt](https://user-images.githubusercontent.com/7629077/89518010-a045e900-d7da-11ea-95d6-03726dc2ccd4.gif)

### What you expected to happen
I would like to log in to passbolt once for day, session, not every time i try to use this extension.

**Comment by stripthis** [comment] 2020-08-06 10:26
Duplicate of https://github.com/passbolt/passbolt_browser_extension/issues/90

**Closed by stripthis** 2020-08-06 10:26 UTC

**Comment by stripthis** [comment] 2020-08-06 10:35
@burasuk if you do not click on "remember me" it will ask the passphrase everytime. The passphrase is also flushed when the browser is in idle mode, as mentioned in the linked issue.
