### ISSUE TITLE
Page is not loading correctly, passwords are no longer accessible

### ISSUE THREAD

**Issue by ralphhaselbach** [passbolt/passbolt_browser_extension#115] opened 2021-01-27 09:55 UTC
## Page is not loading correctly, passwords are no longer accessible
* Passbolt Version: passbolt-ce-server/buster,now 2.13.5-1 all [installed]
* Platform and Target:
-- Browser: Tested with various browsers
--- Chrome: Version 88.0.4324.104 (Offizieller Build) (64-Bit)
--- Firefox: Version 85.0 (64-bit)
-- Web server: nginx; nginx/stable,stable,now 1.14.2-2+deb10u3 all [installed]
-- Web Extension version 3.0.0

### What you did
Extension was auto-updated, when I wasn't able to access the passwords anymore I've installed the latest Debian updates and migrated Passbolt from an installation with installation scripts (v1) to the Debian package using the guide on passbolt.com. This didn't solve the issue so I found and tried the steps from [Issue 113](https://github.com/passbolt/passbolt_browser_extension/issues/113):
`sudo -H -u www-data bash -c "./bin/cake passbolt datacheck --hide-success-details"`
![PassboltDatacheck](https://user-images.githubusercontent.com/54543286/105973446-070ed580-608d-11eb-9268-0fd30c13e865.png)

` sudo -H -u www-data bash -c "./bin/cake passbolt cleanup --dry-run"`
![PassboltCleanup](https://user-images.githubusercontent.com/54543286/105973465-0e35e380-608d-11eb-8535-04efe189bae1.png)

### What happened
Passbolt login works however the page with the passwords is not loaded, also cannot access users tab or profile settings:
![PassboltLoadingError](https://user-images.githubusercontent.com/54543286/105973054-91a30500-608c-11eb-896b-05879e0dc582.png)

Browser console error shown:
![PassboltConsoleError](https://user-images.githubusercontent.com/54543286/105972670-28bb8d00-608c-11eb-83fd-f24bebcfa3f3.png)

### What you expected to happen
Access the passwords again.

**Comment by sajtdavid** [comment] 2021-01-27 10:04
Same here. Most users can access their passwords, my user have this issue: EntityValidationError: Could not validate entity Avatar at Function.validateObject.

Happens on clean install, Chrome & Firefox too, multiple PCs.

Data check:
```
[FAIL] Data integrity for Favorites.
  [FAIL] Can validate: 1/2
    [FAIL] Validation failed for favorite 59aeaf6f-6380-439a-8c71-1153c0a802c8. {"foreign_model":{"inList":"The provided value is invalid"}}
```

**Comment by nourcy** [comment] 2021-01-27 10:08
Hi @ralphhaselbach, can you share the content of the details json object? (with an obfuscation of any sensitive data of course)
And also, are you able to access your profile under /app/settings/profile to see if you avatar is available?

**Comment by ralphhaselbach** [comment] 2021-01-27 10:24
Hi @nourcy, here is the log file when saving the console error, I wasn't able to save it in another format: 
[PassboltConsoleError.log](https://github.com/passbolt/passbolt_browser_extension/files/5879426/PassboltConsoleError.log)

Accessing the profile page the page looks like this as well:
![PassboltProfilePage](https://user-images.githubusercontent.com/54543286/105977777-12b0cb00-6092-11eb-9ba1-7ec9307e7410.png)

When trying to edit my profile using the profile button I get more error messages:
![PassboltProfilePageEdit](https://user-images.githubusercontent.com/54543286/105977872-2d833f80-6092-11eb-9a60-69db4582018e.png)

**Comment by stripthis** [comment] 2021-01-27 10:50
@ralphhaselbach it seems there is an issue with the avatar data, where user_id is not set (which is strange, probably due to some v1 avatar that have not been correctly migrated), which is not caught by the cleanup script. 

We will be working on a fix to fail better in this scenario.Can you paste the content of https://yoururl.com/users/me.json (please remove names and other sensitive info).In the meantime can you check the content of the file_storage table, in your SQL database:
```
select id, user_id from file_storage;
```

You can then drop the records directly if user_id not set / not a string.
```
delete from file_storage where user_id is NULL;
delete from file_storage where user_id is '';
```

**Comment by rcrdo520** [comment] 2021-01-27 11:37
[me.zip](https://github.com/passbolt/passbolt_browser_extension/files/5879872/me.zip)

Here is mine. I have the same issue. :)

**Comment by nourcy** [comment] 2021-01-27 11:49
@ralphhaselbach, does the database cleaning helps?
Ok @rcrdo520 thanks for the file we will look into it

**Comment by sajtdavid** [comment] 2021-01-27 12:02
> Same here. Most users can access their passwords, my user have this issue: EntityValidationError: Could not validate entity Avatar at Function.validateObject.
> 
> Happens on clean install, Chrome & Firefox too, multiple PCs.
> 
> Data check:
> 
> ```
> [FAIL] Data integrity for Favorites.
>   [FAIL] Can validate: 1/2
>     [FAIL] Validation failed for favorite 59aeaf6f-6380-439a-8c71-1153c0a802c8. {"foreign_model":{"inList":"The provided value is invalid"}}
> ```
My datacheck error was caused by having "resource" instead of "Resource" in the favorites.foreign_model column, after fixing it there are no errors in the datacheck, but the JS error is still there.

Here is my json:
[me.zip](https://github.com/passbolt/passbolt_browser_extension/files/5880005/me.zip)

**Comment by stripthis** [comment] 2021-01-27 12:08
@sajtdavid can you confirm you have the same error message e.g. `details: user_id: {...}`. If so can you show me the result of the following query:
```
select id, user_id from file_storage;
```

I'm trying to narrow down the validation error so that we can relax it. 
We have a fix ready for user_id that we are publishing now with v3.0.1 but more information about the data would be great. It seems to be affecting users that have been there since the v1.

Apologies for the inconvenience,

**Comment by rcrdo520** [comment] 2021-01-27 12:13
This was mine.

`select id, user_id from file_storage;

| id                                   | user_id                              |
| 3f35f5bc-2423-40a0-b31c-824fb6674b48 | NULL                                 |
| 4bd27228-4b13-4275-bb64-ff3e483c8197 | NULL                                 |
| 54227f02-7e41-4c9b-b56d-87fb09b64586 | 5a9d1119-4020-40d7-9d02-5160c0a8051b |
| 94115495-d216-4b1f-9228-a15bb556b155 | NULL                                 |
| a7452d7b-55cc-4496-8e0c-e591b1ed6d76 | 5a941c02-6814-40df-b9e8-6118c0a8051b |
| b23b86c5-612f-41f4-bf83-c5408eb73b2c | NULL                                 |
6 rows in set (0.00 sec)

delete from file_storage where user_id is NULL;
Query OK, 4 rows affected (0.04 sec)

select id, user_id from file_storage;

| id                                   | user_id                              |
| 54227f02-7e41-4c9b-b56d-87fb09b64586 | 5a9d1119-4020-40d7-9d02-5160c0a8051b |
| a7452d7b-55cc-4496-8e0c-e591b1ed6d76 | 5a941c02-6814-40df-b9e8-6118c0a8051b |
2 rows in set (0.00 sec)`

**Comment by ralphhaselbach** [comment] 2021-01-27 12:14
The database query listed 3 users of which only the first one had a user_id set. The other two were NULL. I've deleted the entries with the given command and now I can access the users and administration tab as well as the my profile page. The avatar has been reset to the default icon.

The passwords page still shows nothing, it seems like it's loading as there is a loading bar at the bottom:
![PassboltLoading](https://user-images.githubusercontent.com/54543286/105989539-91613480-60a1-11eb-95cf-e0f9505c5a7f.png)

Here is my me-file:
[me.zip](https://github.com/passbolt/passbolt_browser_extension/files/5880045/me.zip)

**Comment by stripthis** [comment] 2021-01-27 12:20
@ralphhaselbach can you get in touch with us at support@passbolt.com, so that we can organize a quick call and have a look together at the issue?

**Comment by stripthis** [comment] 2021-01-27 12:58
OK, so for users coming from V1 so far we have seen:
- Avatar with user_id set to NULL
- Favorites with 'resource' instead of 'Resource' as part of the model.
- Favorites with modified date set to NULL
- Duplicate slugs if using tags

@nourcy is working on a document on how to cleanup the data manually, and we're publishing a new version of the extension which would accept these data from v1.

**Comment by nourcy** [comment] 2021-01-27 13:27
Here is the link guys: https://community.passbolt.com/t/browser-extension-v3-0-0-issues-identified-for-v1-data/3471
We will close this post to centralise.

**Comment by stripthis** [comment] 2021-01-27 13:36
Publishing another hotfix for these issues.
Please check: https://community.passbolt.com/t/browser-extension-v3-0-0-data-issues-identified-for-users-using-passbolt-since-v1/3471

**Closed by stripthis** 2021-01-27 13:36 UTC
Labels: bug
