### ISSUE TITLE
Extension not detected after setup when server does not meet with minimum entropy requirements

### ISSUE THREAD

**Issue by hardcpp** [passbolt/passbolt_browser_extension#193] opened 2023-08-29 18:45 UTC
Hi it's related to #47 i guess.

So a friend couldn't get the extension working for a Passbolt CE Docker under Unraid, the extension was never detected but i finally found the issue.

If the server PGP key is not strong enought (due to low OS entropy) the extension will make a silent error (Can be seen in the chrome dev tool only when inspecting the extension) and not display anything than "Install extension" on the setup page

**Comment by Benj1er** [comment] 2024-02-14 07:07
Hello @hardcpp,

Thank you for your report.
Could you please send a screenshot of the chrome development tool with the issue you encountered?

A follow-up ticket was created on the internal tracker: PB-29858

**Comment by cedricalfonsi** [comment] 2024-10-25 15:37
Since we have not received further information and are unable to reproduce the issue, we are closing this bug report for now. If you encounter the issue again or have additional details, please feel free to reopen the report, and we will be happy to investigate further.

**Closed by cedricalfonsi** 2024-10-25 15:37 UTC
