### ISSUE TITLE
Microsoft SSO - No login window

### ISSUE THREAD

**Issue by kempfsolutions** [passbolt/passbolt_browser_extension#185] opened 2023-05-25 10:56 UTC
## No Login Window appears on 
* Passbolt Plugin Version: latest
* Platform and Target:
-- Browser: Chrome & Firefox

### What happened
If i click on the Microsoft login button, now loginwindow appears
![Screenshot 2023-05-25 113158](https://github.com/passbolt/passbolt_browser_extension/assets/2961851/45863d0b-1092-4ca6-b495-ab3e026e3270)

### What you expected to happen
The login window should appear.

**Comment by Gamabunta57** [comment] 2023-06-08 08:20
Hello @kempfsolutions !

A fix has been provided for this issue. It's available on the version 4.0.3 of the browser extension. 
Currently, this version is available for Google Chrome. For the other stores (Egde and Mozilla), the browser extension is still in review by their team and we are waiting for it to be released.

If you can and have a bit of time, could you confirm the issue is fixed on your side for Chrome please 🙏 ?

**Closed** 2023-06-13 15:51 UTC
