### ISSUE TITLE
Passbolt extension stops being detected as installed. 

### ISSUE THREAD

**Issue by BigPuppyDev** [passbolt/passbolt_browser_extension#81] opened 2019-06-18 05:36 UTC
Passbolt extension stops being detected as installed after a day. Reinstalling several times needed for it to be detected again and account has to be recovered.

* Passbolt Version: 2.10.0
* Platform and Target:
-- Browser: Chrome  74.0.3729.131 (64 bit)
-- Web server: nginx/1.12.2 - PHP 7.2.19 /Centos 7.6.1810
-- etc.: Browser running on Arch Linux and Ubuntu.

### What you did/What happened
I installed the extension, and recovered my account. The next day, Passbolt opens and asks to install the extension as if it was never installed. Reinstalling the extension does not make it be detected without closing the browser and then reinstalling. The day after the same issue will occur all over again.

### What you expected to happen
Passbolt extension to remain detected.
As you can see from the image the extension is installed but not detected.
![Screenshot_20190618_083358](https://user-images.githubusercontent.com/33845447/59655726-f2c1e180-91a3-11e9-927b-c4724b89f70f.png)

**Comment by stripthis** [comment] 2019-06-18 05:40
@BigPuppyDev we are aware of the issue, this seems to be a new behavior when the browser gets updated in the background. Next time this happen try to restart the browser instead of reinstalling the extension. We're looking into a way of reproducing / fixing this.

**Comment by BigPuppyDev** [comment] 2019-06-20 07:31
@stripthis Confirmed. Closing the browser and opening it again makes the extension detected again, and without having to recover account. However I even had to close the browser completely, even the background  process running in the taskbar.

**Comment by stripthis** [comment] 2019-12-06 11:56
Closing as stalled / we cannot reproduce. Feel free to reopen if you see occurring again.

**Closed by stripthis** 2019-12-06 11:56 UTC
Labels: bug, cannot reproduce
